config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :contacts do
    member do
      post 'add_to_friends/:friend_id' => 'contacts#add_to_friends', as: :add_to_friends
      delete 'remove_from_friends/:friend_id' => 'contacts#remove_from_friends', as: :remove_from_friends
    end
  end

  root 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :contacts

  validates :name, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :company
  has_many :friendships
  has_many :friends, through: :friendships

  validates :name, presence: true

  def friend_with?(contact)
    friendships.where(friend_id: contact.id).present?
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :contact
  belongs_to :friend, class_name: 'Contact'

  validate :friendship_can_only_be_within_a_company

  private

  def friendship_can_only_be_within_a_company
    if contact.company != friend.company
      errors[:base] << 'A friendship can not be established because the contact belongs to the different company'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to companies_url, notice: 'Company was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy, :add_to_friends, :remove_from_friends]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @all_other_contacts_in_company = @contact.company.contacts.where.not(id: @contact.id)
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_url, notice: 'Contact was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_to_friends
    @friendship = @contact.friendships.build(friend_id: params[:friend_id])
    @friendship.save
  end

  def remove_from_friends
    @friendship = @contact.friendships.where(friend_id: params[:friend_id]).first
    @friendship.destroy
    @friend_id =  params[:friend_id]
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :company_id, :friend_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/companies/_form.html.erb
<%= form_for @company, html: {class: "form-horizontal company"} do |f| %>

    <% if @company.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@company.errors.count, "error") %> prohibited this company from being
              saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @company.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="control-group">
      <%= f.label :name, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <%= error_span(@company[:name]) %>
    </div>
    <br/>

    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', default: t("helpers.links.cancel")), companies_path, class: 'btn btn-default' %>

<% end %>

app/views/companies/edit.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companies/index.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%= t '.actions', default: t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.name, company_path(company) %></td>
        <td><%= l company.created_at %></td>
        <td>
          <%= link_to t('.edit', default: t("helpers.links.edit")),
                      edit_company_path(company), class: 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', default: t("helpers.links.destroy")),
                      company_path(company),
                      method: :delete,
                      data: {confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?'))},
                      class: 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")), new_company_path, class: 'btn btn-primary' %>

app/views/companies/new.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companies/show.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @company.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              companies_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_company_path(@company), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              company_path(@company),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/contacts/_add_to_friends.html.erb
<%= link_to 'Add To Friends', add_to_friends_contact_path(contact, friend), class: 'btn btn-primary btn-xs pull-right', remote: true, method: :post %>

app/views/contacts/_form.html.erb
<%= form_for @contact, html: {class: 'form-horizontal contact'} do |f| %>

    <% if @contact.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@contact.errors.count, 'error') %> prohibited this contact from being
              saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @contact.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="control-group">
      <%= f.label :name, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <%= error_span(@contact[:name]) %>
    </div>
    <div class="control-group">
      <%= f.label :company_id, class: 'control-label' %>
      <div class="controls">
        <%= f.select :company_id, Company.all.collect { |x| [x.name, x.id] }, {}, class: 'form-control' %>
      </div>
      <%= error_span(@contact[:company_id]) %>
    </div>

    <br/>
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), contacts_path, class: 'btn btn-default' %>
<% end %>

app/views/contacts/_remove_from_friends.html.erb
<%= link_to 'Remove From Friends', remove_from_friends_contact_path(contact, friend), class: 'btn btn-primary btn-xs pull-right', remote: true, method: :delete  %>

app/views/contacts/add_to_friends.js.erb
<% if @friendship.valid? %>
  $('span#friend_actions_<%= @friendship.friend.id %>').html('<%= render partial: 'remove_from_friends', locals: {contact: @friendship.contact, friend: @friendship.friend} %>')
<% end %>

app/views/contacts/edit.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/contacts/index.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:company_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= link_to contact.name, contact_path(contact) %></td>
        <td><%= contact.company.name %></td>
        <td><%=l contact.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_contact_path(contact), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      contact_path(contact),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_contact_path,
            :class => 'btn btn-primary' %>

app/views/contacts/new.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/contacts/remove_from_friends.js.erb
$('span#friend_actions_<%= @friend_id %>').html('<%= render partial: 'add_to_friends', locals: {contact: @contact, friend: @friend_id} %>');

app/views/contacts/show.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%= t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @contact.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:company_id) %>:</strong></dt>
  <dd><%= @contact.company.name %></dd>
</dl>

<div class="panel panel-default">
  <div class="panel-heading">My Company Contacts</div>

  <ul class="list-group">
    <% @all_other_contacts_in_company.each do |contact| %>
        <li class="list-group-item ">
          <%= contact.name %>
          <span id="friend_actions_<%= contact.id %>">
            <% if @contact.friend_with?(contact) %>
              <%= render partial: 'remove_from_friends', locals: {contact: @contact, friend: contact} %>
            <% else %>
              <%= render partial: 'add_to_friends', locals: {contact: @contact, friend: contact} %>
            <% end %>
          </span>
        </li>
    <% end %>
  </ul>
</div>

<%= link_to t('.back', default: t("helpers.links.back")), contacts_path, class: 'btn btn-default' %>
<%= link_to t('.edit', default: t("helpers.links.edit")), edit_contact_path(@contact), class: 'btn btn-default' %>
<%= link_to t('.destroy', default: t("helpers.links.destroy")),
            contact_path(@contact),
            method: 'delete',
            data: {confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?'))},
            class: 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CompanyAndContacts</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= nav_bar brand: 'Companies and Contacts' do %>
    <%= menu_group do %>
        <%= menu_item "Companies", root_path %>
        <%= menu_item "Contacts", contacts_path %>
    <% end %>
<% end %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>